### ISSUE TITLE
'docker build'-step of tye deploy fails when project is not on system drive

### ISSUE THREAD

**Issue by SebastianLng** [dotnet/tye#153]
### Describe the bug
The 'tye deploy' command fails when the project is not on the system drive. The 'docker build' step results in an error.

### To Reproduce
Create and deploy a solution on a drive other than the system drive:
```
dotnet new razor -n frontend
dotnet new sln
dotnet sln add frontend
tye deploy --interactive
```

This results in the following error:

![error](https://user-images.githubusercontent.com/25402641/77123309-0a363f80-6a40-11ea-8944-6699a3ad0eef.jpg)

These steps work on the system drive and fail on any other.

### Further technical details
- Version: 0.1.0-alpha.20168.8+f45b9444d4894009bde48e2a3411a52dd09497b1
- Windows 10 1909
- Docker Desktop 2.2.0.4

**Comment by rynowak** [comment]
Thanks for the report! We'll fix this.

**Comment by rynowak** [comment]
This should be fixed as of `0.1.0-alpha.20174.3` - I don't have easy access to a windows machine to test it right now, so please let us know if you hit issues.

**Comment by SebastianLng** [comment]
The build still fails with the same error:
![builderror](https://user-images.githubusercontent.com/25402641/77545035-1ee45e80-6eaa-11ea-955e-1f65ea07476c.jpg)

**Comment by rynowak** [comment]
Ok, I'll take a look at this again.

**Comment by rynowak** [comment]
@SebastianLng -  I cannot reproduce this failure. I suspect I may have told you the wrong version for the fix 😢 

The fix was to publish to a temp folder instead of inside the app's folder. Relevant bit from the logs (which I don't see in your example) 

```txt
Running 'dotnet publish'.
        > dotnet publish "D:\testing\testing.csproj" -c Release -o "C:\Users\rynowak.REDMOND\AppData\Local\Temp\pyaopkfm.cmx"
            Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
            Copyright (C) Microsoft Corporation. All rights reserved.
            
              Restore completed in 33.83 ms for D:\testing\testing.csproj.
              You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
              testing -> D:\testing\bin\Release\netcoreapp3.1\testing.dll
              testing -> C:\Users\rynowak.REDMOND\AppData\Local\Temp\pyaopkfm.cmx\
        Done running 'dotnet publish' exit code: 0
        Created Publish Output: 'Microsoft.Tye.TempDirectory'
```

If you're still seeing this can you pass `-v debug` and include the output?

Here's what I get using `tye build -v debug` (this does the container build step).

```txt
> tye --version
0.1.0-alpha.20208.4+3f994be2fd4b9acaebb69a896141e154ffe9ae36
```

```txt
Locating .NET SDK...
Found .NET SDK at: C:\Program Files\dotnet\sdk\3.1.200-preview-015002\
Registered .NET SDK.Loading project 'D:\testing\testing.csproj'.
Loaded project 'D:\testing\testing.csproj'.
Build started 4/8/2020 5:56:21 PM.
__________________________________________________
Project "D:\testing\testing.csproj" (Restore;ResolveReferences;ResolvePackageDependenciesDesignTime;PrepareResources;GetAssemblyAttributes target(s)):

Target _FilterRestoreGraphProjectInputItems:
    __________________________________________________
    Project "D:\testing\testing.csproj" is building "D:\testing\testing.csproj" (_IsProjectRestoreSupported target(s)):

Target _GetAllRestoreProjectPathItems:
    __________________________________________________
    Project "D:\testing\testing.csproj" is building "D:\testing\testing.csproj" (_GenerateRestoreProjectPathWalk target(s)):

    __________________________________________________
    Project "D:\testing\testing.csproj" is building "D:\testing\testing.csproj" (_IsProjectRestoreSupported target(s)):

Target _GenerateRestoreGraph:
    __________________________________________________
    Project "D:\testing\testing.csproj" is building "D:\testing\testing.csproj" (_GenerateRestoreGraphProjectEntry target(s)):

    __________________________________________________
    Project "D:\testing\testing.csproj" is building "D:\testing\testing.csproj" (_GenerateProjectRestoreGraph target(s)):

Target Restore:
    Committing restore...
    Assets file has not changed. Skipping assets file writing. Path: D:\testing\obj\project.assets.json
    Restore completed in 45.23 ms for D:\testing\testing.csproj.
    
    NuGet Config files used:
        C:\Users\rynowak.REDMOND\AppData\Roaming\NuGet\NuGet.Config
        C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
    
    Feeds used:
        https://api.nuget.org/v3/index.json
        C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.65
Found application version: 1.0.0
RunCommand=D:\testing\bin\Debug\netcoreapp3.1\testing.exe
RunArguments=
TargetPath=D:\testing\bin\Debug\netcoreapp3.1\testing.dll
PublishDir=bin\Debug\netcoreapp3.1\publish\
AssemblyName=testing
IntermediateOutputPath=obj\Debug\netcoreapp3.1\
Found target framework: netcoreapp3.1
Found shared frameworks: Microsoft.NETCore.App, Microsoft.AspNetCore.App
IsAspNet=True
Evaluation Took: 945.8777ms
Processing Service 'testing'...
    Compiling Services...
    Done Compiling Services...
    Publishing Project...
        Running 'dotnet publish'.
        > dotnet publish "D:\testing\testing.csproj" -c Release -o "C:\Users\rynowak.REDMOND\AppData\Local\Temp\pyaopkfm.cmx"
            Microsoft (R) Build Engine version 16.5.0+d4cbfca49 for .NET Core
            Copyright (C) Microsoft Corporation. All rights reserved.
            
              Restore completed in 33.83 ms for D:\testing\testing.csproj.
              You are using a preview version of .NET Core. See: https://aka.ms/dotnet-core-preview
              testing -> D:\testing\bin\Release\netcoreapp3.1\testing.dll
              testing -> C:\Users\rynowak.REDMOND\AppData\Local\Temp\pyaopkfm.cmx\
        Done running 'dotnet publish' exit code: 0
        Created Publish Output: 'Microsoft.Tye.TempDirectory'
    Done Publishing Project...
    Building Docker Image...
        Writing Dockerfile to 'C:\Users\rynowak.REDMOND\AppData\Local\Temp\pyaopkfm.cmx\Dockerfile'.
        Done writing Dockerfile.
        Running 'docker build'.
        > docker build "C:\Users\rynowak.REDMOND\AppData\Local\Temp\pyaopkfm.cmx" -t testing:1.0.0 -f "C:\Users\rynowak.REDMOND\AppData\Local\Temp\pyaopkfm.cmx\Dockerfile"
            Sending build context to Docker daemon  290.8kB
            
            Step 1/4 : FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
             ---> e2cd20adb129
            Step 2/4 : WORKDIR /app
             ---> Using cache
             ---> 2b4aaeb2d6f3
            Step 3/4 : COPY . /app
             ---> Using cache
             ---> e39a5848b8a1
            Step 4/4 : ENTRYPOINT ["dotnet", "testing.dll"]
             ---> Using cache
             ---> 6f16231dc917
            Successfully built 6f16231dc917
            Successfully tagged testing:1.0.0
            SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x' permissions. It is recommended to double check and reset permissions for sensitive files and directories.
        Done running 'docker build' exit code: 0
        Created Docker Image: 'testing:1.0.0'
    Done Building Docker Image...
Done Processing Service 'testing'...

```

**Comment by SebastianLng** [comment]
I tried it again with the new release 0.1.0-alpha.20209.5+e3fc0045bd1e5913da935241874761929f1e8465

It works for me now, looks like you did fix it :)
![tye](https://user-images.githubusercontent.com/25402641/78997646-417fa400-7b47-11ea-8295-49822c9505fa.jpg)

**Comment by jkotalik** [comment]
Awesome!

**Comment by rynowak** [comment]
I'm glad it's working for you. Sorry for the confusion. My guess is that I told you the wrong build to try.

**Comment by bedrierol** [comment]
I've encountered this issue:

windows 10 

c:\temp\ms>tye --version
0.10.0-alpha.21420.1+7cec0655cc474aee8d3c3a3d180678985209d439

c:\temp\ms>tye deploy -i
Loading Application Details...
Verifying kubectl installation...
Verifying kubectl connection to cluster...
Processing Service 'frontend'...
    Applying container defaults...
    Compiling Services...
    Publishing Project...
    Building Docker Image...
            "docker build" requires exactly 1 argument.
            See 'docker build --help'.

            Usage:  docker build [OPTIONS] PATH | URL | -

            Build an image from a Dockerfile
Drats! 'deploy' failed:
        'docker build' failed.
