### ISSUE TITLE
Support for .NET full framework?

### ISSUE THREAD

**Issue by JohanPetersson** [dotnet/tye#517]
Would it be possible, during development, to have a front-end or backend built on MVC .NET full framework, i.e not .NET Core?

If yes, what would be the requirements to support this scenario, migrating to SDK style project (which I believe works pretty well)?

I assume this would only work smoothly on a Windows machine though.

This would be really helpful for all out there in the process of migrating old solutions. 

Today we have a bunch of PS scripts launching IIS Express and all services. It works ok but the experience is not the best. Would be really nice to get rid of these.

**Comment by davidfowl** [comment]
This isn't something we plan to tackle but would take contributions for (assuming it's well tested). It's come up here as well https://github.com/dotnet/tye/issues/137.

**Comment by jkotalik** [comment]
There are certain levels which we could support .NET Framework. I see a few levels here:

### Being able to run a .NET Framework project

As a first step, you could probably set the iisexpress executable via doing the following:
```
services:
- name: myservice
  executable: iisexpress.exe (maybe full path if not on the path)
  args: <args necessary to start app>
```

### Enabling service discovery for this project

We probably would need to make the Microsoft.Tye.Extensions package netstandard2.0 s.t. it can be used on framework apps.

### Building .NET Framework apps

I'm not sure what would be required here, but there would need to be a bit of work for getting the right logic with msbuild to build .NET Framework projects


Those are all of the big blockers I see right now. If anyone is willing to add these, we would take contributions for it.

**Comment by spboyer** [comment]
Support could be added in a docker mode only.

**Comment by Kralizek** [comment]
I just landed on a project heavily based on .NET Framework and we plan on migrate it to .NET 8 by leveraging YARP.

I'm planing on using Tye to tie together all the different dependencies (SQL server, Elasticsearch and Redis are strong dependencies)

I'm looking for a way to feed into the old FX app the port number and address of those services. It currents is hosted on IIS express (locally).

**Comment by Kralizek** [comment]
@JohanPetersson could you please link the PR where this issue is solved?

**Comment by JohanPetersson** [comment]
@Kralizek this is not solved, and I don't expect it to ever be. That's why I closed it.

**Comment by JohanPetersson** [comment]
@Kralizek it's not solved, and I expect it to never be. That's why I closed it.
